// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlastiPack.API.Data;

#nullable disable

namespace PlastiPack.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507021114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlastiPack.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nit")
                        .HasColumnType("text")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("integer")
                        .HasColumnName("stock_disponible");

                    b.Property<int>("StockReservado")
                        .HasColumnType("integer")
                        .HasColumnName("stock_reservado");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.HasIndex("ReferenciaId")
                        .IsUnique();

                    b.ToTable("inventario");
                });

            modelBuilder.Entity("PlastiPack.API.Models.OrdenProceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("NombreProceso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_proceso");

                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_produccion_id");

                    b.Property<int>("Secuencia")
                        .HasColumnType("integer")
                        .HasColumnName("secuencia");

                    b.HasKey("Id");

                    b.HasIndex("OrdenProduccionId");

                    b.ToTable("orden_procesos");
                });

            modelBuilder.Entity("PlastiPack.API.Models.OrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadRequerida")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_requerida");

                    b.Property<Guid?>("CreadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ReferenciaId");

                    b.ToTable("ordenes_produccion");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destino");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VendedorId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("PlastiPack.API.Models.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ReferenciaId");

                    b.ToTable("pedido_detalle");
                });

            modelBuilder.Entity("PlastiPack.API.Models.PedidoHistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_nuevo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pedido_historial_estado");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Planilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("SelladroaId")
                        .HasColumnType("integer")
                        .HasColumnName("selladora_id");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("SelladroaId");

                    b.ToTable("planillas");
                });

            modelBuilder.Entity("PlastiPack.API.Models.PlanillaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("OrdenProcesoId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_proceso_id");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("integer")
                        .HasColumnName("planilla_id");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer")
                        .HasColumnName("posicion");

                    b.HasKey("Id");

                    b.HasIndex("OrdenProcesoId");

                    b.HasIndex("PlanillaId");

                    b.ToTable("planilla_items");
                });

            modelBuilder.Entity("PlastiPack.API.Models.PrecioReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric")
                        .HasColumnName("precio");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_desde");

                    b.HasKey("Id");

                    b.HasIndex("ReferenciaId");

                    b.ToTable("precios_referencia");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Referencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Alto")
                        .HasColumnType("numeric")
                        .HasColumnName("alto");

                    b.Property<decimal?>("Ancho")
                        .HasColumnType("numeric")
                        .HasColumnName("ancho");

                    b.Property<decimal?>("Calibre")
                        .HasColumnType("numeric")
                        .HasColumnName("calibre");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("text")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("ColoresImpresion")
                        .HasColumnType("text")
                        .HasColumnName("colores_impresion");

                    b.Property<decimal?>("CostoProduccion")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_produccion");

                    b.Property<Guid?>("CreadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<decimal?>("FuelleDerecho")
                        .HasColumnType("numeric")
                        .HasColumnName("fuelle_derecho");

                    b.Property<decimal?>("FuelleFondo")
                        .HasColumnType("numeric")
                        .HasColumnName("fuelle_fondo");

                    b.Property<decimal?>("FuelleIzquierdo")
                        .HasColumnType("numeric")
                        .HasColumnName("fuelle_izquierdo");

                    b.Property<decimal?>("FuelleSuperior")
                        .HasColumnType("numeric")
                        .HasColumnName("fuelle_superior");

                    b.Property<string>("Grupo")
                        .HasColumnType("text")
                        .HasColumnName("grupo");

                    b.Property<bool>("Impresion")
                        .HasColumnType("boolean")
                        .HasColumnName("impresion");

                    b.Property<decimal?>("Impuesto")
                        .HasColumnType("numeric")
                        .HasColumnName("impuesto");

                    b.Property<string>("MateriaPrima")
                        .HasColumnType("text")
                        .HasColumnName("materia_prima");

                    b.Property<string>("Medida")
                        .HasColumnType("text")
                        .HasColumnName("medida");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Presentacion")
                        .HasColumnType("text")
                        .HasColumnName("presentacion");

                    b.Property<string>("ReferenciCorta")
                        .HasColumnType("text")
                        .HasColumnName("referencia_corta");

                    b.Property<string>("TipoCliente")
                        .HasColumnType("text")
                        .HasColumnName("tipo_cliente");

                    b.Property<string>("TipoImpresion")
                        .HasColumnType("text")
                        .HasColumnName("tipo_impresion");

                    b.Property<string>("TipoProducto")
                        .HasColumnType("text")
                        .HasColumnName("tipo_producto");

                    b.Property<string>("TipoSellado")
                        .HasColumnType("text")
                        .HasColumnName("tipo_sellado");

                    b.Property<string>("TratadoCara")
                        .HasColumnType("text")
                        .HasColumnName("tratado_cara");

                    b.Property<string>("Troquelado")
                        .HasColumnType("text")
                        .HasColumnName("troquelado");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("text")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.ToTable("referencias");
                });

            modelBuilder.Entity("PlastiPack.API.Models.RegistroSellado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadUnidades")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_unidades");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("OperarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("operario_id");

                    b.Property<decimal>("PesoDesperdicio")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_desperdicio");

                    b.Property<int>("PlanillaItemId")
                        .HasColumnType("integer")
                        .HasColumnName("planilla_item_id");

                    b.Property<int>("RolloId")
                        .HasColumnType("integer")
                        .HasColumnName("rollo_id");

                    b.HasKey("Id");

                    b.HasIndex("OperarioId");

                    b.HasIndex("PlanillaItemId");

                    b.HasIndex("RolloId");

                    b.ToTable("registros_sellado");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Rollo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("MarcaImpresa")
                        .HasColumnType("text")
                        .HasColumnName("marca_impresa");

                    b.Property<string>("NumeroRollo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_rollo");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_kg");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("referencia_id");

                    b.Property<bool>("TieneImpresion")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_impresion");

                    b.HasKey("Id");

                    b.HasIndex("ReferenciaId");

                    b.ToTable("rollos");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Selladora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("selladoras");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Inventario", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Referencia", "Referencia")
                        .WithOne("Inventario")
                        .HasForeignKey("PlastiPack.API.Models.Inventario", "ReferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referencia");
                });

            modelBuilder.Entity("PlastiPack.API.Models.OrdenProceso", b =>
                {
                    b.HasOne("PlastiPack.API.Models.OrdenProduccion", "OrdenProduccion")
                        .WithMany("Procesos")
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenProduccion");
                });

            modelBuilder.Entity("PlastiPack.API.Models.OrdenProduccion", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("CreadoPor");

                    b.HasOne("PlastiPack.API.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlastiPack.API.Models.Referencia", "Referencia")
                        .WithMany()
                        .HasForeignKey("ReferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Referencia");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Pedido", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("PlastiPack.API.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PlastiPack.API.Models.PedidoDetalle", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlastiPack.API.Models.Referencia", "Referencia")
                        .WithMany()
                        .HasForeignKey("ReferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Referencia");
                });

            modelBuilder.Entity("PlastiPack.API.Models.PedidoHistorialEstado", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Pedido", "Pedido")
                        .WithMany("Historial")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlastiPack.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Planilla", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("CreadoPor");

                    b.HasOne("PlastiPack.API.Models.Selladora", "Selladora")
                        .WithMany()
                        .HasForeignKey("SelladroaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Selladora");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("PlastiPack.API.Models.PlanillaItem", b =>
                {
                    b.HasOne("PlastiPack.API.Models.OrdenProceso", "OrdenProceso")
                        .WithMany()
                        .HasForeignKey("OrdenProcesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlastiPack.API.Models.Planilla", "Planilla")
                        .WithMany("Items")
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenProceso");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("PlastiPack.API.Models.PrecioReferencia", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Referencia", "Referencia")
                        .WithMany("Precios")
                        .HasForeignKey("ReferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referencia");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Referencia", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("CreadoPor");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("PlastiPack.API.Models.RegistroSellado", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Usuario", "Operario")
                        .WithMany()
                        .HasForeignKey("OperarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlastiPack.API.Models.PlanillaItem", "PlanillaItem")
                        .WithMany("Registros")
                        .HasForeignKey("PlanillaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlastiPack.API.Models.Rollo", "Rollo")
                        .WithMany()
                        .HasForeignKey("RolloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operario");

                    b.Navigation("PlanillaItem");

                    b.Navigation("Rollo");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Rollo", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Referencia", "Referencia")
                        .WithMany()
                        .HasForeignKey("ReferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referencia");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Usuario", b =>
                {
                    b.HasOne("PlastiPack.API.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PlastiPack.API.Models.OrdenProduccion", b =>
                {
                    b.Navigation("Procesos");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Planilla", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PlastiPack.API.Models.PlanillaItem", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Referencia", b =>
                {
                    b.Navigation("Inventario");

                    b.Navigation("Precios");
                });

            modelBuilder.Entity("PlastiPack.API.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
